import React, { useState } from 'react';
import { useMetadataStorage } from '../../hooks/useMetadataStorage';
import './JobDescriptionsTab.css';

export default function JobDescriptionsTab() {
  const db = useMetadataStorage();
  
  const [selectedItemType, setSelectedItemType] = useState('TEMPLATE'); // TEMPLATE or ANALYSIS
  const [selectedId, setSelectedId] = useState(null);
  
  const [showAnalysisModal, setShowAnalysisModal] = useState(false);
  const [analysisForm, setAnalysisForm] = useState({ templateId: '', department: '', location: '' });

  const [viewFormat, setViewFormat] = useState('DETAYLI'); // 'KISA', 'DETAYLI', 'ILAN'

  // Trees derived from DB
  const roleTemplates = db.roleTemplates || [];
  const jobAnalyses = db.jobAnalyses || [];

  const handleCreateAnalysis = () => {
    if(!analysisForm.templateId || !analysisForm.department || !analysisForm.location) return;
    
    const sourceTemplate = roleTemplates.find(t => t.id === analysisForm.templateId);
    if(!sourceTemplate) return;

    db.saveJobAnalysis({
      ...sourceTemplate, // clone all fields (items, etc)
      sourceTemplateId: sourceTemplate.id,
      department: analysisForm.department,
      location: analysisForm.location,
      analysisStatus: 'DRAFT',
      id: undefined // will be generated by the hook
    });
    
    setShowAnalysisModal(false);
  };

  const getSelectedItem = () => {
    if(selectedItemType === 'TEMPLATE') return roleTemplates.find(t => t.id === selectedId);
    return jobAnalyses.find(a => a.id === selectedId);
  };

  const selectedData = getSelectedItem();

  const renderContentByFormat = () => {
    if (!selectedData) return null;

    // Helper to map items
    const competencies = selectedData.items?.filter(i => { const l = db.library.find(x=>x.id===i.libraryItemId); return l && l.type === 'COMPETENCY'; }) || [];
    const tasks = selectedData.items?.filter(i => { const l = db.library.find(x=>x.id===i.libraryItemId); return l && l.type === 'TASK'; }) || [];
    
    if (viewFormat === 'KISA') {
      return (
        <div className="ja-format-kisa fade-in">
          <h3 style={{ borderBottom: '2px solid #E2E8F0', paddingBottom: '0.5rem' }}>Özet Rol Çerçevesi</h3>
          <p><strong>Temel Amacı:</strong> {selectedData.jobFamily} ailesinde yer alan bu rol seviyesine uygun temel operasyonların yürütülmesinden sorumludur.</p>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', marginTop: '1.5rem' }}>
            <div>
              <h4 style={{ color: '#475569', marginBottom: '0.5rem' }}>Kritik Sorumluluklar (&gt;%15)</h4>
              <ul style={{ paddingLeft: '1.2rem', color: '#334155' }}>
                {tasks.filter(t => t.weight >= 15).map(t => {
                   const libItem = db.library.find(x=>x.id===t.libraryItemId);
                   return <li key={t.libraryItemId}>{libItem?.name}</li>;
                })}
                {tasks.filter(t => t.weight >= 15).length === 0 && <li>Büyük ağırlıklı görev atanmamış.</li>}
              </ul>
            </div>
            <div>
              <h4 style={{ color: '#475569', marginBottom: '0.5rem' }}>Zorunlu Yetkinlikler</h4>
              <ul style={{ paddingLeft: '1.2rem', color: '#16A34A', fontWeight: 500 }}>
                {competencies.filter(c => c.isRequired).map(c => {
                   const libItem = db.library.find(x=>x.id===c.libraryItemId);
                   return <li key={c.libraryItemId}>{libItem?.name}</li>;
                })}
              </ul>
            </div>
          </div>
        </div>
      );
    }

    if (viewFormat === 'ILAN') {
      return (
        <div className="ja-format-ilan fade-in" style={{ padding: '2rem', background: '#FAFAF9', borderRadius: '12px', border: '1px solid #E7E5E4' }}>
          <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
             <h2 style={{ color: '#1C1917', fontSize: '2rem', marginBottom: '0.5rem' }}>Takım arkadaşı arıyoruz!</h2>
             <h3 style={{ color: '#D97706', margin: 0 }}>{selectedData.name} ({selectedItemType === 'ANALYSIS' ? selectedData.location : 'Global'})</h3>
             {selectedItemType === 'ANALYSIS' && <p style={{ color: '#78716C', marginTop: '0.5rem' }}>{selectedData.department} Departmanı</p>}
          </div>

          {selectedData.jobSummary && (
             <div style={{ marginBottom: '2rem', padding: '1.5rem', background: '#FFFBEB', borderRadius: '8px', borderLeft: '4px solid #D97706' }}>
                <h4 style={{ color: '#B45309', marginTop: 0 }}>Rolün Amacı</h4>
                <p style={{ color: '#78350F', lineHeight: 1.8, margin: 0 }}>{selectedData.jobSummary}</p>
             </div>
          )}

          <h4 style={{ color: '#292524' }}>Senden Neler Bekliyoruz? (Görev Tanımın)</h4>
          <ul style={{ color: '#44403C', lineHeight: 1.8, marginBottom: '2rem' }}>
             {tasks.map(t => {
                const libItem = db.library.find(x=>x.id===t.libraryItemId);
                return <li key={t.libraryItemId}>{libItem?.name} {t.note ? <em style={{ color: '#78716C' }}>({t.note})</em> : ''}</li>;
             })}
          </ul>

          <h4 style={{ color: '#292524' }}>Aradığımız Nitelikler ve Beceriler</h4>
          <ul style={{ color: '#44403C', lineHeight: 1.8, marginBottom: '2rem' }}>
             {selectedData.education && <li><strong>Eğitim:</strong> {selectedData.education}</li>}
             {selectedData.experience && <li><strong>Deneyim:</strong> {selectedData.experience}</li>}
             {competencies.map(c => {
                const libItem = db.library.find(x=>x.id===c.libraryItemId);
                return <li key={c.libraryItemId}>{libItem?.name} {c.isRequired ? <strong style={{color:'#D97706'}}>(Zorunlu)</strong> : ''}</li>;
             })}
          </ul>
          
          <div style={{ textAlign: 'center', marginTop: '3rem' }}>
             <button className="ji-btn primary" style={{ background: '#D97706' }}>İlanı Çıktı Al (PDF)</button>
          </div>
        </div>
      );
    }

    // Default: DETAYLI
    return (
      <div className="ja-jd-body fade-in">
        <div className="ja-grid-2">
           <div className="ja-section">
             <h4 className="ja-section-title">Temel Sorumluluklar & Görevler</h4>
             <ul className="ja-list">
               {tasks.map(t => {
                 const libItem = db.library.find(x=>x.id===t.libraryItemId);
                 return (
                   <li key={t.libraryItemId} style={{ marginBottom: '0.75rem' }}>
                     <strong>{libItem?.name}</strong> <span style={{ color: '#94A3B8', fontSize: '0.8rem' }}>(Ağırlık: %{t.weight})</span>
                     {t.note && <div style={{ fontSize: '0.85rem', color: '#64748B', marginTop: '0.2rem' }}>Not: {t.note}</div>}
                   </li>
                 );
               })}
             </ul>
           </div>
           <div className="ja-section">
             <h4 className="ja-section-title">Aranan Nitelikler</h4>
             <div className="ja-req-box">
               <div className="ja-req-item"><strong>Eğitim:</strong> {selectedData.education || 'Belirtilmedi'}</div>
               <div className="ja-req-item"><strong>Kıdem/Deneyim:</strong> {selectedData.experience || 'Belirtilmedi'}</div>
             </div>
           </div>
        </div>

        <div className="ja-section">
           <h4 className="ja-section-title" style={{ display: 'flex', justifyContent: 'space-between' }}>
             <span>Davranışsal ve Teknik Yetkinlikler</span>
             <span style={{ fontSize: '0.8rem', fontWeight: 500, color: '#94A3B8' }}>Ağırlık Skalası</span>
           </h4>
           <div className="ja-competencies-grid">
             {competencies.map(comp => {
               const libItem = db.library.find(x=>x.id===comp.libraryItemId);
               // Normalization for visual 0-100 bar, assuming a weight corresponds to bar fill conceptually
               return (
                 <div key={comp.libraryItemId} className="ja-comp-item">
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                      <strong style={{ fontSize: '0.85rem', color: '#1E293B' }}>{libItem?.name}</strong>
                      <span style={{ fontSize: '0.85rem', fontWeight: 700, color: '#4F46E5' }}>% {comp.weight}</span>
                    </div>
                    <div className="ja-progress-bg">
                      <div 
                        className="ja-progress-fill" 
                        style={{ 
                           width: `${comp.weight}%`,
                           background: comp.weight >= 20 ? '#4F46E5' : comp.weight >= 10 ? '#6366F1' : '#818CF8'
                        }}
                      ></div>
                    </div>
                 </div>
               );
             })}
           </div>
        </div>
      </div>
    );
  };

  return (
    <div className="job-analysis-container fade-in">
      
      {/* ─── MODAL ALANI (İŞ ANALİZİ ATAMA) ─── */}
      {showAnalysisModal && (
        <div className="ja-modal-overlay">
          <div className="ja-modal glass-card fade-in">
            <h3 style={{ marginTop: 0 }}>📋 İş Analizi Oluştur</h3>
            <p style={{ color: '#64748B', fontSize: '0.9rem', marginBottom: '1.5rem' }}>
              Master şablonu alarak, belirli bir departman ve lokasyona ait 'İş Analizi Kaydı'na (Gerçek Pozisyon) dönüştürün.
            </p>
            
            <div style={{ marginBottom: '1rem' }}>
              <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.5rem' }}>Kaynak Rol Şablonu</label>
              <select className="ji-input" value={analysisForm.templateId} onChange={e => setAnalysisForm({...analysisForm, templateId: e.target.value})}>
                <option value="">Şablon Seçin...</option>
                {roleTemplates.map(t => <option key={t.id} value={t.id}>{t.name} (v{t.version})</option>)}
              </select>
            </div>
            
            <div style={{ marginBottom: '1rem' }}>
              <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.5rem' }}>Şirket İçi Departman</label>
              <input className="ji-input" value={analysisForm.department} onChange={e => setAnalysisForm({...analysisForm, department: e.target.value})} placeholder="Örn: EMEA Satış Operasyonları" />
            </div>
            
            <div style={{ marginBottom: '2rem' }}>
              <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.5rem' }}>Lokasyon / Tesis</label>
              <input className="ji-input" value={analysisForm.location} onChange={e => setAnalysisForm({...analysisForm, location: e.target.value})} placeholder="Örn: Maslak / İstanbul" />
            </div>
            
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem' }}>
              <button className="ji-btn ghost" onClick={() => setShowAnalysisModal(false)}>İptal</button>
              <button className="ji-btn primary" onClick={handleCreateAnalysis}>Analiz Kaydını Başlat</button>
            </div>
          </div>
        </div>
      )}

      {/* ─── HEADER ALANI ─── */}
      <div className="ja-header glass-card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ margin: 0, color: '#1E293B', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            💼 İş Analizi ve Rol Kataloğu
          </h2>
          <p style={{ margin: '0.5rem 0 0', color: '#64748B', fontSize: '0.9rem' }}>
            AI ile yeni yetkinlik profilleri üretin veya hazır şablonları departmanlarınıza atayın.
          </p>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button className="ji-btn ghost" style={{ color: '#8B5CF6', borderColor: '#8B5CF6', fontWeight: 600 }} onClick={() => alert('Lütfen AI Profil Kurulum Sihirbazı sekmesine geçin (veya bu butona yönlendirme ekleyin).')}>
             ✨ AI ile Profil Üret
          </button>
          <button className="ji-btn primary" onClick={() => setShowAnalysisModal(true)}>
             + Şablondan Atama Yap
          </button>
        </div>
      </div>

      <div className="ja-main-layout">
        {/* ─── SOL PANEL: AĞAÇ YAPISI (TREE VIEW) ─── */}
        <div className="ja-sidebar glass-card">
          <div className="ja-sidebar-header">
             <h4 style={{ margin: 0, color: '#334155' }}>🏢 Görüntülenecek Kayıt Türü</h4>
             <select 
               className="ji-input" 
               style={{ marginTop: '0.5rem', borderColor: '#CBD5E1' }} 
               value={selectedItemType} 
               onChange={(e) => { setSelectedItemType(e.target.value); setSelectedId(null); }}
             >
               <option value="TEMPLATE">Master Rol Şablonları</option>
               <option value="ANALYSIS">Aktif İş Analizi Kayıtları</option>
             </select>
          </div>
          
          <div className="ja-tree">
            {selectedItemType === 'TEMPLATE' && roleTemplates.map(t => (
               <div 
                 key={t.id} 
                 className={`ja-tree-item ${selectedId === t.id ? 'active' : ''}`}
                 onClick={() => setSelectedId(t.id)}
               >
                 <div className="ja-tree-item-dot"></div>
                 <div style={{ flex: 1 }}>
                   <div className="ja-job-title">{t.name} <span style={{fontSize:'0.7rem', color:'#94A3B8'}}>(v{t.version})</span></div>
                   <div className="ja-job-level">{t.jobFamily} • {t.level}</div>
                 </div>
               </div>
            ))}
            {selectedItemType === 'TEMPLATE' && roleTemplates.length === 0 && <div style={{padding:'1rem', textAlign:'center', color:'#94A3B8', fontSize:'0.85rem'}}>Şablon bulunmuyor.</div>}

            {selectedItemType === 'ANALYSIS' && jobAnalyses.map(a => (
               <div 
                 key={a.id} 
                 className={`ja-tree-item ${selectedId === a.id ? 'active' : ''}`}
                 onClick={() => setSelectedId(a.id)}
               >
                 <div className="ja-tree-item-dot" style={{ background: '#F59E0B' }}></div>
                 <div style={{ flex: 1 }}>
                   <div className="ja-job-title">{a.name}</div>
                   <div className="ja-job-level">{a.department} • {a.location}</div>
                 </div>
               </div>
            ))}
            {selectedItemType === 'ANALYSIS' && jobAnalyses.length === 0 && <div style={{padding:'1rem', textAlign:'center', color:'#94A3B8', fontSize:'0.85rem'}}>Aktif iş analizi bulunmuyor. Öncelikle AI Sihirbazından profil üretin veya şablondan atama yapın.</div>}
          </div>
        </div>

        {/* ─── SAĞ PANEL: GÖREV TANIMI KARTI ─── */}
        <div className="ja-content">
          {selectedData ? (
            <div className="ja-jd-card glass-card fade-in">
              <div className="ja-jd-header" style={{ flexDirection: 'column' }}>
                 <div style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'flex-start' }}>
                    <div>
                       <span className="ja-badge" style={{ background: selectedItemType === 'TEMPLATE' ? '#EEF2FF' : '#FEF3C7', color: selectedItemType === 'TEMPLATE' ? '#4F46E5' : '#B45309' }}>
                         {selectedItemType === 'TEMPLATE' ? 'MASTER ŞABLON' : 'İŞ ANALİZİ KAYDI'}
                       </span>
                       <h2 style={{ margin: '0.5rem 0 0', color: '#0F172A', fontSize: '1.8rem' }}>{selectedData.name}</h2>
                       <div style={{ display: 'flex', gap: '1rem', marginTop: '0.75rem' }}>
                          <span className="ja-tag"><span style={{color: '#94A3B8'}}>Seviye:</span> {selectedData.level}</span>
                          {selectedItemType === 'ANALYSIS' && <span className="ja-tag"><span style={{color: '#94A3B8'}}>Departman:</span> {selectedData.department}</span>}
                          {selectedItemType === 'ANALYSIS' && <span className="ja-tag"><span style={{color: '#94A3B8'}}>Lokasyon:</span> {selectedData.location}</span>}
                       </div>
                    </div>
                    <div className="ja-jd-actions">
                       {/* Format Segmented Control */}
                       <div style={{ display: 'flex', background: '#E2E8F0', padding: '0.25rem', borderRadius: '8px' }}>
                          <button className={`ji-btn ${viewFormat === 'KISA' ? 'primary' : 'ghost'}`} style={{ padding: '0.4rem 0.8rem', borderRadius: '6px', fontSize: '0.75rem', boxShadow: 'none' }} onClick={() => setViewFormat('KISA')}>Özet</button>
                          <button className={`ji-btn ${viewFormat === 'DETAYLI' ? 'primary' : 'ghost'}`} style={{ padding: '0.4rem 0.8rem', borderRadius: '6px', fontSize: '0.75rem', boxShadow: 'none' }} onClick={() => setViewFormat('DETAYLI')}>Detaylı</button>
                          <button className={`ji-btn ${viewFormat === 'ILAN' ? 'primary' : 'ghost'}`} style={{ padding: '0.4rem 0.8rem', borderRadius: '6px', fontSize: '0.75rem', boxShadow: 'none' }} onClick={() => setViewFormat('ILAN')}>İlan (Job Ad)</button>
                       </div>
                    </div>
                 </div>
              </div>

              {/* Dinamik Üretici Çıktısı */}
              <div style={{ padding: '2rem' }}>
                 {renderContentByFormat()}
              </div>

            </div>
          ) : (
            <div className="ja-empty-state glass-card">
              <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>📄</div>
              <h3>Görüntülenecek Kayıt Seçilmedi</h3>
              <p style={{ color: '#94A3B8' }}>Detayları okumak veya formatlamak için sol panelden bir kayıt seçin.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
